version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-stretch-node

    working_directory: /home/circleci

    steps:
      - checkout:
          path: /home/circleci/repo

      - run:
          name: Checkout
          command: |
            git clone --depth 1 https://github.com/adobe/commerce-cif-connector.git

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}
            - maven-repo-v1-

      - run:
          name: Build
          working_directory: /home/circleci/commerce-cif-connector
          command: node /home/circleci/repo/.circleci/ci/build.js
  
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}

      - persist_to_workspace:
          root: /home/circleci/commerce-cif-connector
          paths:
            - configuration.json
            - bundles/*/target/*.jar
            - content/*/target/*.zip
            - it/content/target/*.zip


  integration-tests-652:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3-jdk11
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:6.5.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:
      - checkout:
          path: /home/circleci/repo

      - run:
          name: Checkout
          command: git clone --depth 1 https://github.com/adobe/commerce-cif-connector.git

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}
            - maven-repo-v1-

      - attach_workspace:
          at: /home/circleci/cq/commerce-cif-connector

      - run:
          name: Integration tests
          command: node /home/circleci/repo/.circleci/ci/it-tests.js
          working_directory: /home/circleci/cq/commerce-cif-connector

      - store_test_results:
          path: /home/circleci/cq/commerce-cif-connector/it/http/target/failsafe-reports

      - store_artifacts:
          path: /home/circleci/cq/commerce-cif-connector/it/http/target/failsafe-reports


  integration-tests-646:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3-jdk8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:6.4.6
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:
      - checkout:
          path: /home/circleci/repo

      - run:
          name: Checkout
          command: git clone --depth 1 https://github.com/adobe/commerce-cif-connector.git

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}
            - maven-repo-v1-

      - attach_workspace:
          at: /home/circleci/cq/commerce-cif-connector

      - run:
          name: Integration tests
          command: node /home/circleci/repo/.circleci/ci/it-tests.js
          working_directory: /home/circleci/cq/commerce-cif-connector

      - store_test_results:
          path: /home/circleci/cq/commerce-cif-connector/it/http/target/failsafe-reports

      - store_artifacts:
          path: /home/circleci/cq/commerce-cif-connector/it/http/target/failsafe-reports


  cypress-tests:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:cq650-latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:

      - checkout:
          path: repo

      - restore_cache:
          keys: 
            - cypress-cache-v1-{{ checksum "repo/e2e-testing/package.json" }}
            - cypress-cache-v1-

      - run:
          name: Prepare E2E tests
          command: |
            cd repo/e2e-testing
            npm ci
            npm run cy:verify

      - run:
          name: Download CIF Demo project
          command: curl -vL https://github.com/adobe/aem-cif-project-archetype/releases/download/cif-project-archetype-0.5.0/demo-store.all-0.5.0.zip --output demo-store.all-0.5.0.zip

      - run:
          name: Connect to QP
          command: ./qp.sh -v bind --server-hostname localhost --server-port 55555

      - run:
          name: Start CQ
          command: >
            ./qp.sh -v start --id author --runmode author --port 4502 --qs-jar cq-quickstart.jar
            --install-file /home/circleci/cq/demo-store.all-0.5.0.zip

      - run:
          name: Test Homepage
          command: |
            cd repo/e2e-testing
            npm test

      - store_artifacts:
          path: /home/circleci/cq/repo/e2e-testing/cypress/screenshots/

      - store_artifacts:
          path: /home/circleci/cq/repo/e2e-testing/cypress/videos/

      - store_test_results:
          path: /home/circleci/cq/repo/e2e-testing/results

      - run:
          name: Stop CQ
          command: ./qp.sh -v stop --id author

      - save_cache:
          paths:
            - ~/cache
          key: cypress-cache-v1-{{ checksum "repo/e2e-testing/package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - build
      - integration-tests-652:
          requires:
            - build
      - integration-tests-646:
          requires:
            - build
#      - cypress-tests