version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-stretch

    working_directory: /home/circleci

    steps:
      - run:
          name: Checkout
          command: |
            git clone --depth 1 https://github.com/adobe/commerce-cif-connector.git

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}
            - maven-repo-v1-

      - run:
          name: Build
          working_directory: /home/circleci/commerce-cif-connector
          command: |
            java -version
            mvn -v
            mvn -B clean install

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}

      - persist_to_workspace:
          root: /home/circleci/commerce-cif-connector
          paths:
            - bundles/*/target/*.jar
            - content/*/target/*.zip
            - it/content/target/*.zip


  integration-tests:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:cq650-latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:
      - run:
          name: Checkout
          command: |
            git clone --depth 1 https://github.com/adobe/commerce-cif-connector.git

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "commerce-cif-connector/pom.xml" }}
            - maven-repo-v1-

      - attach_workspace:
          at: /home/circleci/cq/commerce-cif-connector

      - run:
          name: Connect to QP
          command: ./qp.sh -v bind --server-hostname localhost --server-port 55555

      - run:
          name: Start CQ
          command: >
            ./qp.sh -v start --id author --runmode author --port 4502 --qs-jar cq-quickstart.jar
            --bundle org.apache.sling:org.apache.sling.junit.core:1.0.23:jar
            --bundle com.adobe.commerce.cif:graphql-client:1.1.1:jar
            --bundle com.adobe.commerce.cif:magento-graphql:4.0.0-magento233:jar
            --bundle com.adobe.cq:core.wcm.components.all:2.4.0:zip
            --install-file /home/circleci/cq/commerce-cif-connector/bundles/cif-connector-graphql/target/cif-connector-graphql-0.6.0-SNAPSHOT.jar
            --install-file /home/circleci/cq/commerce-cif-connector/bundles/cif-virtual-catalog/target/cif-virtual-catalog-0.6.0-SNAPSHOT.jar
            --install-file /home/circleci/cq/commerce-cif-connector/content/cif-connector/target/cif-connector-content-0.6.0-SNAPSHOT.zip
            --install-file /home/circleci/cq/commerce-cif-connector/content/cif-virtual-catalog/target/cif-virtual-catalog-content-0.6.0-SNAPSHOT.zip
            --install-file /home/circleci/cq/commerce-cif-connector/it/content/target/it-test-content-0.1.3-SNAPSHOT.zip

      - run:
          name: Integration Tests
          command: >
            mvn clean verify -U -B
            -Ptest-all
            -Dsling.it.instance.url.1=http://localhost:4502
            -Dsling.it.instance.runmode.1=author
            -Dsling.it.instances=1
          working_directory: /home/circleci/cq/commerce-cif-connector/it/http

      - store_test_results:
          path: /home/circleci/cq/commerce-cif-connector/it/http/target/failsafe-reports

      - store_artifacts:
          path: /home/circleci/cq/commerce-cif-connector/it/http/target/failsafe-reports

      - run:
          name: Stop CQ
          command: ./qp.sh -v stop --id author


  cypress-tests:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:cq650-latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:

      - checkout:
          path: repo

      - run:
          name: Prepare E2E tests
          command: |
            cd repo/e2e-testing
            npm install

      - run:
          name: Download CIF Demo project
          command: curl -vL https://github.com/adobe/aem-cif-project-archetype/releases/download/cif-project-archetype-0.5.0/demo-store.all-0.5.0.zip --output demo-store.all-0.5.0.zip

      - run:
          name: Connect to QP
          command: ./qp.sh -v bind --server-hostname localhost --server-port 55555

      - run:
          name: Start CQ
          command: >
            ./qp.sh -v start --id author --runmode author --port 4502 --qs-jar cq-quickstart.jar
            --install-file /home/circleci/cq/demo-store.all-0.5.0.zip

      - run:
          name: Test Homepage
          command: |
            curl -v -u 'admin:admin' http://localhost:4502/content/venia.html
            cd repo/e2e-testing
            npm test

      - run:
          name: Stop CQ
          command: ./qp.sh -v stop --id author

workflows:
  version: 2
  build:
    jobs:
#       - build
#      - integration-tests:
#          requires:
#            - build
      - cypress-tests