version: 2.1

jobs:
  integration-tests:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:cq650-latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:
      - run:
          name: Build CIF connector
          command: |
            git clone --depth 1 https://github.com/adobe/commerce-cif-connector.git
            cd commerce-cif-connector
            mvn clean install
            ls -aslh
            pwd

      - run:
          name: Start CQ
          command: |
            ls -aslh
            ./qp.sh -v bind --server-hostname localhost --server-port 55555
            ./qp.sh -v start --id author --runmode author --port 4502 --qs-jar cq-quickstart.jar \ 
              --bundle com.adobe.commerce.cif:graphql-client:1.1.1:jar \
              --bundle com.adobe.commerce.cif:magento-graphql:4.0.0-magento233:jar \
              --install-file commerce-cif-connector/bundles/cif-connector-graphql/target/cif-connector-graphql-0.6.0-SNAPSHOT.jar \
              --install-file commerce-cif-connector/bundles/cif-virtual-catalog/target/cif-virtual-catalog-0.6.0-SNAPSHOT.jar \
              --install-file commerce-cif-connector/content/cif-connector/target/cif-connector-content-0.6.0-SNAPSHOT.zip \
              --install-file commerce-cif-connector/content/cif-virtual-catalog/target/cif-virtual-catalog-content-0.6.0-SNAPSHOT.zip
            curl -v -u 'admin:admin' http://localhost:4502
            ./qp.sh -v stop --id author

workflows:
  version: 2
  build:
    jobs:
      - integration-tests