version: 2.1

jobs:
  integration-tests:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:cq650-latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/cq

    steps:
      - run:
          name: Download Venia Store
          command: |
            curl -v https://github.com/adobe/aem-cif-project-archetype/releases/download/latest/demo-store.all-1.0.0.zip --output demo-store.all.zip
            ls -aslh

      - run:
          name: Start CQ
          command: |
            ls -aslh
            ./qp.sh -v bind --server-hostname localhost --server-port 55555
            ./qp.sh -v start --id author --runmode author --port 4502 --qs-jar cq-quickstart.jar --install-file demo-store.all.zip
            curl -v -u 'admin:admin' http://localhost:4502/content/venia.html
            ./qp.sh -v stop --id author

workflows:
  version: 2
  build:
    jobs:
      - integration-tests